{{- if .Values.midpoint.keystore.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "midpoint.fullname" . }}-keystore-config
  labels:
    app: {{ template "midpoint.name" . }}
    chart: {{ template "midpoint.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
{{- range .Values.midpoint.keystore.certificates }}
  {{ .name }}: |
{{ .certificate | indent 4 }}
{{- end }}
{{- end }}