apiVersion: v1
kind: Secret
metadata:
  name: {{ template "midpoint.fullname" . }}
  labels:
    app: {{ template "midpoint.name" . }}
    chart: {{ template "midpoint.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  keystore-password: {{ .Values.midpoint.keystore.password | b64enc | quote }}
